### ISSUE TITLE
Error in handle

### ISSUE THREAD

**Issue by mgolkardev** [php-telegram-bot/example-bot#1]
Hi

i have error in hook.php

Longman\TelegramBot\Exception\TelegramException: Duplicate update received! in /var/www/example.me/public_html/vendor/longman/telegram-bot/src/DB.php:486

I'm used webhook method.
please help me

**Comment by noplanman** [comment]
What version are you using?
Please make sure that you are on version 0.44.1 👍 

(also for next time, post your issue on the core repository here: https://github.com/php-telegram-bot/core)

**Comment by mgolkardev** [comment]
Ok, Thanks
