### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by Pakev** [php-telegram-bot/example-bot#18]
How to start the Bot?

**Comment by noplanman** [comment]
@Pakev please read through the readme for information:
https://github.com/php-telegram-bot/example-bot/blob/master/README.md

You can also check the readme of the core library here:
https://github.com/php-telegram-bot/core/blob/master/README.md

**Comment by satory33** [comment]
How to start?

**Comment by noplanman** [comment]
See my comment above.

You do need some knowledge of PHP and composer to work with this library.
