### ISSUE TITLE
I've try using this example, but i get this error

### ISSUE THREAD

**Issue by luiguild** [php-telegram-bot/example-bot#2]
PHP Fatal error: Class 'TelegramBot\TelegramBotManager\BotManager' not found in manager.php

anyone can help me?

**Comment by jacklul** [comment]
To use `manager.php` you will have to `composer require php-telegram-bot/telegram-bot-manager` into the project.

**Comment by noplanman** [comment]
@jacklul Good idea, just to be safe.
