### ISSUE TITLE
Call to undefined method Longman\TelegramBot\Telegram::deleteWebhook()

### ISSUE THREAD

**Issue by ShadowSonic** [php-telegram-bot/example-bot#26]
`2018/09/20 11:52:12 [error] 7896#7896: *1558 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method Longman\TelegramBot\Telegram::deleteWebhook() in /home/vhosts/telegram/htdocs/unset.php:16
`

Tested the Tutorial and found this in my error-logs. Used here: [Tutorial](https://github.com/php-telegram-bot/example-bot/blob/master/unset.php)

**Comment by noplanman** [comment]
Are you sure you have the latest version of the bot?
Did you install it via Composer?

Please check `Telegram.php` and see what version you have

**Comment by ShadowSonic** [comment]
Installed via composer today.

Telegram.php says
`class Telegram
{
    /**
     * Version
     *
     * @var string
     */
    protected $version = '0.35.0';
`

**Comment by noplanman** [comment]
Right, the latest version is `0.54.0`, so yours is outdated.

What version of PHP are you on?

**Comment by ShadowSonic** [comment]
Ah, i think thats the problem. I have 2 php versions, and my default CLI-php = 5.6
I have a look how i can call composer with 7.x

Thanks

**Comment by ShadowSonic** [comment]
Missing mbstring.

Thanks for your help.
