### ISSUE TITLE
botAddedInChat() is not working

### ISSUE THREAD

**Issue by yylzcom** [php-telegram-bot/example-bot#34]
When I tried "NewchatmembersCommand.php", I found my bot sent welcome message whether new member is a bot or not.

If changes the code below, it works as expect. 
from (line 51)
`if (!$message->botAddedInChat()) {`
to
`if (!$member->getIsBot())  {`

Please check. Any idea or advice would be highly appreciate.

Thanks in advance.

**Comment by noplanman** [comment]
Those are 2 different things.

[`botAddedInChat`](https://github.com/php-telegram-bot/core/blob/78024d7bc55cebf3987247b465a1009b5186060a/src/Entities/Message.php#L190) returns if the current bot was added to the chat, as not to send itself a message.

Also, remember that the commands found in this repo are examples only and need customising for personal preference!
