### ISSUE TITLE
Remove or update ShortenerCommand.php because of discontinued Botan service

### ISSUE THREAD

**Issue by Joennuh** [php-telegram-bot/example-bot#39]
I was looking arround in the example commands directory and came accros the ShortenerCommand.php example at https://github.com/php-telegram-bot/example-bot/blob/90bfde028f71bda1aedd51bdc225984a68b5c276/Commands/ShortenerCommand.php.
I see the example uses Botan which has been discontinued  according to  the readme of the core project: https://github.com/php-telegram-bot/core/blob/78024d7bc55cebf3987247b465a1009b5186060a/CHANGELOG.md#removed-4
According to this pull request it would have been removed in the development branch: https://github.com/php-telegram-bot/example-bot/pull/31 Schouldn't the change be merged to the master branch too?
Maybe the example can replaced by another shortener service?

I'm sorry if this question may sound stupid to you. I'm not quite an expert with git and Github.

**Comment by noplanman** [comment]
Hi @Joennuh thanks for your input.

The link to the `ShortenerCommand.php` you have posted points to a version of the repository where the command still existed.

The command was deleted in #29.
