### ISSUE TITLE
Infinity send messages to user

### ISSUE THREAD

**Issue by nasserghiasi** [php-telegram-bot/example-bot#4]
I created a sample app same as this project and using bot-manager, after run handle action via browser (l parameter = 2000), the bot sends too many messages (Avg 30 in a minute) to the user (me).
when I run handle action, the bot starts to send messages defined in StartCommand class.
why did this happen?
why doesn't command class handle requested commands from users?

**Comment by noplanman** [comment]
The default interval for the loop is 2 seconds, so 30 per minute sounds right.
Are you using a custom command or adding custom input?

Also, is it the same message that gets sent all the time? Normally messages that have been handled shouldn't be repeatedly sent.

Could you share your `manager.php` (without the secret keys) please?

**Comment by nasserghiasi** [comment]
Fixed: this is database exception and now fixed.
