### ISSUE TITLE
How do I trigger an action for non-command messages (no starting with a slash)?

### ISSUE THREAD

**Issue by amandineevard** [php-telegram-bot/example-bot#44]
Hello 😄 

For some reason, I'd like my bot to send a peanut Gif to every message in a conversation containing the word "peanut".
However, I couldn't find any way to do this as I am only able to create commands for message starting with a slash (e.g. /start, /help, ...).

Is there any way to trigger an action to arbitrary messages as well?

Thank you

**Comment by noplanman** [comment]
Yes! You can use the `GenericmessageCommand`, which will react to any message that comes in.

Take a look at the example to handle special messages in groups here:
https://github.com/php-telegram-bot/example-bot/blob/d29a7b266ecfa43df71db2d28ec7cb94c34b66f9/Commands/Group/GenericmessageCommand.php

You could remove most of the code in the `execute()` method and add your code that checks the message text for `peanut` 😃

**Comment by FWeissenb** [comment]
Where do I place my custom "GenericmessageCommand.php" that it isn't affected by a composer update? 
I have configured a Commands dir in my root path to implement UserCommands (as mentioned in example bot or documentation). Is this the right place?

**Comment by noplanman** [comment]
@FWeissenb As long as it's a folder outside your vendor folder you're safe.
It can be a "Commands" folder on the same level as vendor for example. Then you can add it as a custom commands path in your hook or getUpdates file.

Hope that helps :blush:
