### ISSUE TITLE
Problem with survey

### ISSUE THREAD

**Issue by camoralb** [php-telegram-bot/example-bot#45]
Hi! I am using this template for my custom bot. I need a functionality like the /survey one, but since I am testing it only asks for the name (the first question), i write the name and then nothing happens. It is stuck there. I already h¡gave a look to the database and it is saving the conversation, but only the "state" var. I think it is not coming again from client to bot or viceversa when I write a answert. Could you help me please?

**Comment by noplanman** [comment]
Hi 👋 

Please make sure that you have the correct commands in your folder. In this case, you can get the ones for the conversation feature here:
https://github.com/php-telegram-bot/example-bot/tree/d29a7b266ecfa43df71db2d28ec7cb94c34b66f9/Commands/Conversation

Try to put **only** the `SurveyCommand.php` and `GenericmessageCommand.php` files from there in your custom commands folder.

**Comment by mertizci** [comment]
> Hi 👋
> 
> Please make sure that you have the correct commands in your folder. In this case, you can get the ones for the conversation feature here: https://github.com/php-telegram-bot/example-bot/tree/d29a7b266ecfa43df71db2d28ec7cb94c34b66f9/Commands/Conversation
> 
> Try to put **only** the `SurveyCommand.php` and `GenericmessageCommand.php` files from there in your custom commands folder.

I tried the above changes but its not working. Testing on Php 7.4.3.
