### ISSUE TITLE
custom  database table read,insert,update and delete method

### ISSUE THREAD

**Issue by yewenze-lig** [php-telegram-bot/example-bot#47]
how to create custom database read and insert method like ConversationDB.php  inside  Commands folder
by using php-telegram-bot database handle method  like 
`class ConversationDB extends DB`

**Comment by noplanman** [comment]
You can create your own class and get the current PDO object of the database connection using `Longman\TelegramBot\DB::getPdo();`.

Then you can implement any custom methods you want and use that object to talk with the database.

Hope that helps 😊
