### ISSUE TITLE
Working with Groups

### ISSUE THREAD

**Issue by Sviatoslaff** [php-telegram-bot/example-bot#58]
Hello,
first of all, thank you for the good example as a base for devs.
I'm trying to use _newchatmembers_ and _leftchatmember_ commands. I assigned my bot as admin for a group, but no messsages on chat after joinin or leaving the group. 
Do the functions really work?

**Comment by noplanman** [comment]
Hi @Sviatoslaff, yes, the commands do work but may not have been added correctly to your project.

Maybe check the [Support Bot](https://github.com/php-telegram-bot/support-bot/) project for an example of how these types of commands are added:
- [GenericmessageCommand.php](https://github.com/php-telegram-bot/support-bot/blob/1acf536bf74e84d265156eaedac1945e5fc582bb/commands/GenericmessageCommand.php)
- [NewchatmembersCommand.php](https://github.com/php-telegram-bot/support-bot/blob/1acf536bf74e84d265156eaedac1945e5fc582bb/commands/NewchatmembersCommand.php)

Also, knowledge of PHP is absolutely required to use this library.
