### ISSUE TITLE
using manager.php result in error

### ISSUE THREAD

**Issue by arkhub** [php-telegram-bot/example-bot#6]
PHP Version                              7.1.8-2+ubuntu14.04.1+deb.sury.org+4
guzzlehttp/guzzle                     6.3.0  
guzzlehttp/promises                 v1.3.1 
guzzlehttp/psr7                         1.4.2  PSR-7
longman/ip-tools                      1.2.1  
longman/telegram-bot              0.45.0 
monolog/monolog                    1.23.0 S
php-telegram-bot/telegram-bot-manager 1.2.1  
psr/http-message                      1.0.1  
psr/log                                       1.0.2

After setting bot username (with and without '@'), api key, and all the required information for webhook running it in browser `http://mywebsite.com/botexamples/manager.php?s=mysecretkey&a=set` result in fatal error : 
`Fatal error: Uncaught TelegramBot\TelegramBotManager\Exception\InvalidAccessException: Invalid access in /var/www/html/botexamples/vendor/php-telegram-bot/telegram-bot-manager/src/BotManager.php:578 Stack trace: #0 /var/www/html/botexamples/vendor/php-telegram-bot/telegram-bot-manager/src/BotManager.php(130): TelegramBot\TelegramBotManager\BotManager->validateRequest() #1 /var/www/html/botexamples/manager.php(80): TelegramBot\TelegramBotManager\BotManager->run() #2 {main} thrown in /var/www/html/botexamples/vendor/php-telegram-bot/telegram-bot-manager/src/BotManager.php on line 578`

Running it from command line using `sudo php manager.php a=set` works, but example like /whoami doesn't work, and logging filename shows `{$bot_username}_debug.log` instead of `@mybotname_debug.log`

However setting it manually using set.php runs just fine (all modules works, log filenames also shown correctly).

**Comment by noplanman** [comment]
Hi @arkhub 

First off, your bot username must be without the `@`.

The reason you're getting that error message when calling `manager.php` directly from your browser, is because the library only allows requests from Telegram for security reasons. So even if somebody manages to get your secret key, they still can't access your bot directly.

You must either disable this validation (NOT recommended) or add your IP as a trusted IP to allow direct access (👍).

Have a look at the example configuration in the readme, chapter [Set extra bot parameters](https://github.com/php-telegram-bot/telegram-bot-manager#set-extra-bot-parameters), where you'll see parameters called `validate_request` and `valid_ips`.
In the `valid_ips` array you can add your IP address, then it will work perfectly!

**Comment by arkhub** [comment]
thank you, this explains why running `sudo php manager.php s=secretkey a=set` works, one more question the log files still shows `{$bot_username}_debug.log` instead of the actual botnames (I already omitted the '@' sign), is this normal when running from command line?

**Comment by noplanman** [comment]
No need to use `sudo` to execute PHP, please don't use it. It can be very dangerous to execute a PHP script with root rights!

Nice find regarding the log file names! The quotes are supposed to be double `"`, not single `'`:
```php
'logging'  => [
    'debug'  => __DIR__ . "/{$bot_username}_debug.log",
    'error'  => __DIR__ . "/{$bot_username}_error.log",
    'update' => __DIR__ . "/{$bot_username}_update.log",
],
```

Also, make sure you have `$bot_username` defined!

**Comment by noplanman** [comment]
I've updated the `manager.php` example file :+1:

**Comment by arkhub** [comment]
I made the edit to use double quotes instead one single, and now it shows `_debug.log`, is the $bot_username have to be defined first? I already set it up using in 
`
    $bot = new TelegramBot\TelegramBotManager\BotManager([
        // Add you bot's API key and name
        'api_key'      => 'my:api-key',
        'bot_username' => 'mybotnames',
`
oh and thanks for the sudo part, I forgot I use different user when running from command line because at first it didn't work without sudo.

**Comment by noplanman** [comment]
If you check the updated example, `$bot_username` is defined at the top.
You need to define it separately, as the manager does not automatically add it to the logfile name, which is why your file name is `_debug.log`, because `$bot_username` is empty / not defined.
