### ISSUE TITLE
can I instantiate Redis in CallbackqueryCommand.php...

### ISSUE THREAD

**Issue by XiaomiYe** [php-telegram-bot/example-bot#61]
I instantiate Redis in CallbackqueryCommand  and want to write the data of CallbackqueryCommand into the list. But I don't know what went wrong

**Comment by noplanman** [comment]
@XiaomiYe Please add some code and more context, otherwise nobody can help :blush:

**Comment by XiaomiYe** [comment]
CallbackqueryCommand.php :
    /**
     * Main command execution
     * @return ServerResponse
     * @throws \Exception
     */
    public function execute(): ServerResponse
    {
        $callback_query = $this->getCallbackQuery();
        $callback_data  = $callback_query->getData();
        $data['inline_message_id']    = $callback_query->getId();
        //$callback_query->getInlineMessageId();
        $data['keywords']    = $callback_data;
        TelegramLog::debug(json_encode($data));
        $redisobj = new Redis();
        TelegramLog::debug("instantiate Redis");
        try {
        	$connect = $redisobj->pconnect('127.0.0.1', 6379);
            TelegramLog::debug(json_encode($connect));
        } catch (Exception $e) {
            TelegramLog::error(json_encode($e->getMessage()));
        }
        $redisobj->lpush($data);
        return true;
    }

**Comment by noplanman** [comment]
In your redis-cli you can use the `monitor` command if the value comes through properly:
```
$ redis-cli 
127.0.0.1:6379> monitor
```

Your code should work, but you could try this:
- `->connect` instead of `->pconnect`
- `->lPush` instead of `->lpush`
- log the redis response

```php
$redisobj = new Redis();
TelegramLog::debug('instantiate Redis');
try {
    $connect = $redisobj->connect('127.0.0.1', 6379);
    TelegramLog::debug($connect);

    $result = $redisobj->lPush('bot-list', $data);
    TelegramLog::debug($result);
} catch (Exception $e) {
    TelegramLog::error($e->getMessage());
}
```

**Comment by XiaomiYe** [comment]
I have debugged, but when the code runs to $redisobj = new Redis();, it stops. The log does not reach  TelegramLog::debug('instantiate Redis');

There is no problem with the Redis and PHP environments. I have tested the instantiation of Redis in the statistics directory, and the connection, assignment, and reading data are all OK

**Comment by XiaomiYe** [comment]
Thank you. I have found the problem and solved it

**Comment by noplanman** [comment]
Feel free to share the problem and your solution, so others (and me!) can learn, thanks :smiley:

**Comment by XiaomiYe** [comment]
just Replace with $redisobj=new \Redis();
