### ISSUE TITLE
api key value not carried from manager.php

### ISSUE THREAD

**Issue by arkhub** [php-telegram-bot/example-bot#8]
uncommenting and editing this in manager.php :
```php
        'commands' => [
            'paths'   => [
                __DIR__ . '/Commands',
            ],
            'configs' => [
                'weather' => ['own_api_key' => 'my_own_api_key_here'],
            ],
        ],
```

then running the WeatherCommand result in "api-key not set response", did I do something wrong in settings?

**Comment by noplanman** [comment]
@arkhub I think the problem here is a typo:

`owN_api_key` should be `owM_api_key`

OWM stands for Open Weather Map.

**Comment by arkhub** [comment]
sorry, typo in my example. the one I use in manager.php is actually 'owm_api_key' not 'own_api_key'

**Comment by noplanman** [comment]
And you have the latest [`/weather` command](https://github.com/php-telegram-bot/example-bot/blob/master/Commands/WeatherCommand.php) from the [example repository](https://github.com/php-telegram-bot/example-bot/), right?

It works perfectly for me.

**Comment by arkhub** [comment]
ah my bad, just notice that I've changed the weather protected name into something else for testing, and I have to change that variable too in `'configs' => ['my new name' =>['owm_api_key' => 'my key'],`

sorry about it.
